package types

// ErrorKind is the protected builtin classification carried by every Error.
// Every variant but Other is a unit variant; Other carries the one caller-
// supplied Strand header for a failure with no closed classification.

// ErrorKindVariantNames is the fixed, declaration-ordered variant list. Order
// here is the order ErrorKind.header() derivation, match declaration order,
// and generated tag registration all agree on.
var ErrorKindVariantNames = []string{
	"NotFound",
	"PermissionDenied",
	"AlreadyExists",
	"InvalidInput",
	"InvalidPath",
	"NotADirectory",
	"IsADirectory",
	"DirectoryNotEmpty",
	"ReadOnly",
	"Busy",
	"Interrupted",
	"Cancelled",
	"TimedOut",
	"Unsupported",
	"ResourceExhausted",
	"Closed",
	"AddressInUse",
	"AddressUnavailable",
	"ConnectionRefused",
	"ConnectionReset",
	"ConnectionAborted",
	"HostUnreachable",
	"NetworkUnreachable",
	"BrokenPipe",
	"NotConnected",
	"Other",
}

// errorKindHeaders is the fixed display header for each unit variant. Other
// has no entry here: its header is its own payload, not a fixed string.
var errorKindHeaders = map[string]string{
	"NotFound":           "not found",
	"PermissionDenied":   "permission denied",
	"AlreadyExists":      "already exists",
	"InvalidInput":       "invalid input",
	"InvalidPath":        "invalid path",
	"NotADirectory":      "not a directory",
	"IsADirectory":       "is a directory",
	"DirectoryNotEmpty":  "directory not empty",
	"ReadOnly":           "read only",
	"Busy":               "busy",
	"Interrupted":        "interrupted",
	"Cancelled":          "cancelled",
	"TimedOut":           "timed out",
	"Unsupported":        "unsupported",
	"ResourceExhausted":  "resource exhausted",
	"Closed":             "closed",
	"AddressInUse":       "address in use",
	"AddressUnavailable": "address unavailable",
	"ConnectionRefused":  "connection refused",
	"ConnectionReset":    "connection reset",
	"ConnectionAborted":  "connection aborted",
	"HostUnreachable":    "host unreachable",
	"NetworkUnreachable": "network unreachable",
	"BrokenPipe":         "broken pipe",
	"NotConnected":       "not connected",
}

// ErrorKindType is the protected compiler-owned ErrorKind ADT. It is
// registered as a builtin ADT beside FileMode and Seek: its struct is hand-
// written in hexal/error.h rather than generated by the generic ADT writer.
var ErrorKindType = errorKindType()

func errorKindType() Type {
	variants := make([]AdtVariant, len(ErrorKindVariantNames))
	for index, name := range ErrorKindVariantNames {
		if name == "Other" {
			variants[index] = AdtVariant{Name: name, Payload: []ObjectMember{{Name: "header", Type: StrandType, Use: NewTypeUse(StrandType)}}}
			continue
		}
		variants[index] = AdtVariant{Name: name}
	}
	adt := &AdtType{
		Name:     "ErrorKind",
		CName:    "hex_t_ErrorKind",
		Variants: variants,
		identity: newTypeIdentity(),
	}
	return Type{
		Name:         "ErrorKind",
		CName:        adt.CName,
		CanonicalKey: canonicalNominalKey("ErrorKind", ""),
		Adt:          adt,
		identity:     adt.identity,
	}
}

func init() {
	builtinTypes["ErrorKind"] = ErrorKindType
}

// IsErrorKind reports whether typ is the canonical ErrorKind ADT.
func IsErrorKind(typ Type) bool { return typ.Adt != nil && typ.Adt == ErrorKindType.Adt }

// ErrorKindVariantIndex returns the declaration index of a variant name, or
// -1 if unknown.
func ErrorKindVariantIndex(variant string) int {
	for index, name := range ErrorKindVariantNames {
		if name == variant {
			return index
		}
	}
	return -1
}

// ErrorKindHeader returns the fixed display header for a unit ErrorKind
// variant name. It reports false for Other, whose header is its own payload,
// and for any unknown name.
func ErrorKindHeader(variant string) (string, bool) {
	header, ok := errorKindHeaders[variant]
	return header, ok
}
