package types

// UnicodeCategory is the protected builtin classification of one Unicode
// scalar: the thirty general categories the pinned utf8proc release defines.
// Every variant is a unit variant, and the set is fixed by the Unicode
// standard, so a type-mode match over it is exhaustive without a final else.

// UnicodeCategoryVariantNames is the fixed variant list in utf8proc's
// utf8proc_category_t order, so a runtime category value indexes it directly.
var UnicodeCategoryVariantNames = []string{
	"Cn", "Lu", "Ll", "Lt", "Lm", "Lo",
	"Mn", "Mc", "Me",
	"Nd", "Nl", "No",
	"Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po",
	"Sm", "Sc", "Sk", "So",
	"Zs", "Zl", "Zp",
	"Cc", "Cf", "Cs", "Co",
}

// UnicodeCategoryType is the protected compiler-owned UnicodeCategory ADT. It
// is registered as a builtin ADT beside ErrorKind: its struct is hand-written
// in hexal/string.h rather than generated by the generic ADT writer.
var UnicodeCategoryType = unicodeCategoryType()

func unicodeCategoryType() Type {
	variants := make([]AdtVariant, len(UnicodeCategoryVariantNames))
	for index, name := range UnicodeCategoryVariantNames {
		variants[index] = AdtVariant{Name: name}
	}
	adt := &AdtType{
		Name:     "UnicodeCategory",
		CName:    "hex_t_UnicodeCategory",
		Variants: variants,
		identity: newTypeIdentity(),
	}
	return Type{
		Name:         "UnicodeCategory",
		CName:        adt.CName,
		CanonicalKey: canonicalNominalKey("UnicodeCategory", ""),
		Adt:          adt,
		identity:     adt.identity,
	}
}

func init() {
	builtinTypes["UnicodeCategory"] = UnicodeCategoryType
}

// IsUnicodeCategory reports whether typ is the canonical UnicodeCategory ADT.
func IsUnicodeCategory(typ Type) bool {
	return typ.Adt != nil && typ.Adt == UnicodeCategoryType.Adt
}
